version: "3.7"

services:
    dind:
        build:
            context: .
            target: dev
            dockerfile: ./Dockerfile
        privileged: true
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
            - "3306:3306"
            - "5432:5432"
            - "1025:1025"
            - "8025:8025"
            - "8888:8888"
        volumes:
            - "./:/var/app/:rw"

