#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
# https://gist.github.com/jverdeyen/9c0b247bb8b34c7fae514315db36a23e

CONTAINER="php7.4"
ROOT_DIR="/var/www"

# Fetch the GIT diff and format it as command input:
DIFF=$(git diff -r -p -m -M --full-index --staged | cat)

# Run GrumPHP
(cd "./" && echo "${DIFF}" | docker exec -i $CONTAINER bash -c "/var/www/bin/grumphp git:pre-commit --ansi --skip-success-output")

# Validate exit code of above command
RC=$?
if [ "$RC" != 0 ]; then
  exit $RC;
fi

# Clean exit:
exit 0;
