version: "3.3"

services:
    fouras_apache:
        build:
          context: apache
        ports:
            - "8080:80"
        volumes:
            - "../:/var/www/html/:delegated"

    php7.4:
        container_name: php7.4
        build:
          context: php7.4
        volumes:
            - "../:/var/www/:delegated"
        environment:
            - REDIS_URL=redis://root:@redis:3306/fouras
            - DATABASE_CMS_URL=mysql://root:root@fouras_db/cms
    fouras_db:
        build:
            context: mysql
        command: --default-authentication-plugin=mysql_native_password --sql_mode=""
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=fouras
