version: "3.3"

services:
    apache:
        container_name: apache
        build:
          context: ./apache
        ports:
            - "8080:80"
        volumes:
            - "../:/var/www/html/:delegated"

    php7.2:
        container_name: php7.2
        build:
          context: ./php7.2
        environment:
            - SF_DEBUG=true
        volumes:
            - "../:/var/www/:delegated"
    db:
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        build:
            context: ./mysql
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
