imports:
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true
    assets:
        base_path: '/'

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        profile_pic_dir: '%profile_pic_dir%'
        vendor_service_pic_dir: '%vendor_service_pic_dir%'
        service_pic_dir: '%service_pic_dir%'
        map_icon_dir: '%map_icon_dir%'
        maps_key: '%maps.embedded.api.key%'
        cms_base_url: '%cms_base_url%'


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        url: '%env(DATABASE_URL)%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            main:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/app/config/doctrine'
                prefix: 'Model'
                alias: main

doctrine_migrations:
    # List of namespace/path pairs to search for migrations, at least one required
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/migrations'

    # Connection to use for the migrations
    connection: default

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 190
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'

fos_user:
    from_email: 
        address:        noreply@fouras.com
        sender_name:    Fouras
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Model\User
    group:
        group_class: Model\Group
    registration:
        form:
            type: Form\RegistrationFormType
    service:
        mailer: fos_user.mailer.twig_swift

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

csa_guzzle:
    profiler: '%kernel.debug%'
    clients:
        cms_api:
            config: # you can specify the options as in http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client
                base_uri: '%cms_api_url%'
                timeout: 5.0
                # headers:
                #     Accept: application/vnd.github.v3+json

liip_imagine:
    data_loader: fouras_loader
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/web'
    resolvers :
        default :
            web_path :
                web_root: '%kernel.project_dir%/web'
    cache: default
    filter_sets:
        64x64:
            default_image: /web/assets/images/default/unavailable-64x64.jpg
            quality: 90
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        150x100:
            default_image: /web/assets/images/default/unavailable-150x100.jpg
            quality: 90
            filters:
                thumbnail: { size: [150, 100], mode: outbound }
        300x300:
            default_image: /web/assets/images/default/unavailable-300x300.jpg
            quality: 90
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
        340x240:
            default_image: /web/assets/images/default/unavailable-340x240.jpg
            quality: 90
            filters:
                thumbnail: { size: [340, 240], mode: outbound }
        320x360:
            default_image: /web/assets/images/default/unavailable-320x360.jpg
            quality: 90
            filters:
                thumbnail: { size: [320, 360], mode: outbound }
        440x300:
            default_image: /web/assets/images/default/unavailable-440x300.jpg
            quality: 90
            filters:
                thumbnail: { size: [440, 300], mode: outbound }
