# admin:
#     resource: "@AdminBundle/Controller/"
#     type:     annotation
#     prefix:   /admin

front_homepage:
    path:   /{_locale}
    defaults: {_controller: FrontBundle:Pages:index, _locale: '%locale%'}
    requirements:
        _locale: ar|fr|en

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: ar|fr|en

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
# fos_user_security:
#     resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#     prefix: /{_locale}

app_task:
    resource: "@AppBundle/Resources/config/routing/task.yml"
    prefix: /{_locale}/task
    requirements:
        _locale: ar|fr|en

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ar|fr|en