# admin:
#     resource: "@AdminBundle/Controller/"
#     type:     annotation
#     prefix:   /admin

front_homepage:
    path:   /{_locale}
    defaults: {_controller: Controller\Front\PagesController::index, _locale: '%locale%'}
    requirements:
        _locale: ar|fr|en

front:
    resource: "../../src/Controller/Front"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: ar|fr|en

admin:
    resource: "../../src/Controller/Admin"
    type:     annotation

user_actions:
    resource: 'routing/user.yml'
    prefix: /{_locale}/user
    requirements:
        _locale: ar|fr|en

fos_user_actions:
    resource: 'routing/fos_user.yml'
    prefix: /{_locale}
    requirements:
        _locale: ar|fr|en

couple_actions:
    resource: 'routing/couple.yml'
    prefix: /{_locale}/couple
    requirements:
        _locale: ar|fr|en

vendor_actions:
    resource: 'routing/vendor.yml'
    prefix: /{_locale}/vendor
    requirements:
        _locale: ar|fr|en

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"