# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    # You should uncomment this if you want to use pdo_sqlite
    #database_path: "%kernel.root_dir%/data.db3"

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~

    # A secret key that's used to generate certain security-related tokens
    secret: ThisTokenIsNotSoSecretChangeIt

    gravatar.default_options:
        #default: http://dev.fouras.tn/bundles/front/images/default_profile.jpg
        default: ~
        size: 260
        rating: ~
        border: ~
    profile_pic_dir: 'uploads/profiles/'
    service_pic_dir: 'uploads/services/'
    vendor_service_pic_dir: 'uploads/profiles/vendor_service/'
    map_icon_dir: 'assets/images/icons/'
    upload_service_pic_dir: '%kernel.project_dir%/web/%service_pic_dir%'
    upload_profile_pic_dir: '%kernel.project_dir%/web/%profile_pic_dir%'
    maps.embedded.api.key : AIzaSyC7DfJcfvHtlpZLcEjgivtmjnyXlky0GB4
    default_mailer_sender : 'noreply@fouras.com'

    #cms
    cms_api_url: '%env(CMS_API_URL)%'
    cms_api_key: 8d6f1fbea40c389706b796068ed37505
    cms_base_url: '%env(CMS_BASE_URL)%'

    cms_cat_id:
        blog:
            ar: 17
            fr: 9
            en: ~
        news:
            ar: 10
            fr: 10
            en: 10
        faq:
            ar: 20
            fr: 20
            en: 20
        gallery:
            ar: 23
            fr: 23
            en: 23

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $defaultMailerSender: '%default_mailer_sender%'

    app.form.registration:
        class: Form\RegistrationFormType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: 'form.type', alias: 'app_user_registration_form' }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    Controller\:
        resource: '../../src/Controller/*'

    Infrastructure\Listener\:
        resource: '../../src/Infrastructure/Listener/*'

    Infrastructure\EventSubscriber\:
        resource: '../../src/Infrastructure/EventSubscriber/*'

    Infrastructure\Loader\:
        resource: '../../src/Infrastructure/Loader/*'

    Services\:
        resource: '../../src/Services/*'

    FOS\UserBundle\Form\Factory\FactoryInterface: "@fos_user.profile.form.factory"

    Infrastructure\Listener\LocaleListener:
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    Infrastructure\Listener\UserListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Services\GravatarService:
        arguments: ['%gravatar.default_options%']

    Services\CmsService:
        arguments:
            - '@csa_guzzle.client.cms_api'
            - '%cms_api_key%'
            - '@request_stack'
            - '%cms_cat_id%'

    Infrastructure\Loader\FileSystemLoader:
        arguments:
            - ['%kernel.project_dir%', '%kernel.project_dir%/web']
        tags:
            - { name: "liip_imagine.binary.loader", loader: fouras_loader }

    Gedmo\Timestampable\TimestampableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }