#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;
use Symfony\Component\Dotenv\Dotenv;

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read https://symfony.com/doc/current/setup.html#checking-symfony-application-configuration-and-setup
// for more information
//umask(0000);

set_time_limit(0);

require __DIR__.'/../vendor/autoload.php';
(new Dotenv(true))->load(
    __DIR__.'/../.env',
    __DIR__.'/../.env.dev',
    __DIR__.'/../.env.test'
);

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('APP_ENV') ?: 'dev');
$debug = getenv('APP_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new kernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
