services:
    app.locale_listener:
        class: AppBundle\Listener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    app.user_listener:
        class: AppBundle\Listener\UserListener
        arguments: ['@security.token_storage', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    AppBundle\Services\GravatarService:
        class: AppBundle\Services\GravatarService
        arguments: ['%gravatar.default_options%', '@assets.packages']

    AppBundle\Services\CmsService:
        arguments:
            - '@csa_guzzle.client.cms_api'
            - '%cms_api_key%'
            - '@request_stack'
            - '%cms_cat_id%'
