cms_front_homepage:
    path:     /cms
    defaults: { _controller: CmsFrontBundle:Default:index }

cms_front_bloglist:
    path:     /cms/blog/{id}/{slug}/{page}/{max}
    defaults: { _controller: CmsFrontBundle:Blog:list,  }
    requirements:
        id: '\d+'
        slug: '\w+'
        page: '\d+'
        max: '\d+'

cms_front_menu:
    path:     /cms/menu/{id}
    defaults: { _controller: CmsFrontBundle:Menu:index,  }
    requirements:
        id: '\d+'
        max: '\d+'
