user_profile_edit:
    path:     /profile/edit
    defaults: { _controller: Controller\Front\User\ProfileController::editProfile }

user_preferences:
    path:     /preferences
    defaults: { _controller: Controller\Front\User\UserController::preferences }

user_upload_picture:
    path:     picture-upload
    defaults: { _controller: Controller\Front\User\UserController::pictureUpload }

user_url_create:
    path: /url/create
    defaults: { _controller: Controller\Front\User\UserController::createUrl }

user_url_delete:
    path: /url/{id}/delete
    defaults: { _controller: Controller\Front\User\UserController::deleteUrl }

user_delete_task:
    path:     /task/{id}/delete
    defaults: { _controller: Controller\Front\User\UserController::deleteTask }
    methods:  DELETE